### ISSUE TITLE
map making problem

### ISSUE THREAD

**Issue by CCBest2022** [MaisJamal/Carla_apollo_maps#4]
**Hello, I want to make other maps for the carla_apollo_bridge project, below are my thoughts and ideas. Please help me analyze the following feasibility.**

1. I downloaded the map file from the Openstreetmap website in the format of map.osm
2. Convert map.osm into the map file required by carla and apollo
3. Import the converted map files into carla and apollo respectively.

**But regarding the bridge project, how to change the map file, I have the following questions**

1. There are 5 carla map files on apollo, town1, 2, 3, 4, 5, but why is there only one map file` /carla_apollo_bridge/carla-python-0.9.13/util/opendrive/TownBig.xodr `in carla? Isn't this a one-to-one correspondence?

2. I know the map file of apollo very well, just import it to apollo/modules/map/data.
    but. How does carla's map file change for the bridge project? Is it added to /carla_apollo_bridge/carla-python-0.9.13/util/opendrive, and then through `python carla-python-0.9.13/util/config.py -m **map name** --host 172.17.0.1` switch map?

**Comment by MaisJamal** [comment]
Hello,
1. the maps in Carla exist in UnrealEngine, not in the bridge. The world (3d map) runs in Unrealengine, we use the bridge to get access to the world so we can choose a map, add our ego vehicle or to change the configurations of the world, like the weather ... No file in the bridge has deep info about the map. However, using carla-python-0.9.13/util/config.py you can choose one map out of 12 default maps (Town1, Town2, Town3 ... Town12). Apollo on the other hand, needs the apollo HD map format to run the simulation on the map, and because we have only 5 towns available in this format, you should choose one of them so you can run Carla simulation with Apollo, otherwise Dreamview will not show the needed map.

2. I think I have answered your question in the first point. If you have further questions, don't hesitate asking.

**Comment by CCBest2022** [comment]
Thank you very much, under your guidance, I understand this map aspect better. Thanks again.
I'll keep trying to see if I can add new maps to the bridge project.
